# Generated by Django 6.1.1 on 2026-10-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'Thread', 'verbose_name_plural': 'Threads'},
        ),
        migrations.AddField(
            model_name='thread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
