# Generated by Django 6.1.1 on 2026-10-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_options_alter_thread_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
